use_frameworks!

platform :ios, '8.0'

target 'XJPrefrenceTestKit_Example' do
  pod 'XJPrefrenceTestKit', :path => '../'

  target 'XJPrefrenceTestKit_Tests' do
    inherit! :search_paths

    
  end
end
